# 更新本仓库readme的action
# 主要逻辑是可手动调用、api调用、定时调用
# 调用后执行仓库下的update.sh 并使用 secrets.GT (对应值为申请的github token) 完成commit并推送

name: up
on:
  # 手动调用
  workflow_dispatch:

  # api远程调用
  repository_dispatch:
    types: up

  # 定时调用(每小时)
  schedule:
    - cron: '0 * * * *'

jobs:
  up:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Up
        run: |
          bash update.sh
          git status
          git diff
          if [ "$(git diff)" ]; then
            remote_addr=`git remote get-url --push origin`
            remote_addr=`echo $remote_addr|  awk -F '://' '{print $2}'`
            remote_addr=https://${user_name}:${{ secrets.GT }}@${remote_addr}
            echo $remote_addr
            git config  user.name "yaocccc"
            git config  user.email "flyforest@outlook.com"
            git remote add action ${remote_addr}
            git add --all
            git commit -m "BY:GITHUB ACTION -- $(date '+%Y/%m/%d %H:%M')"
            git push action HEAD:master --force
          fi
