# 更新本仓库readme的action
# 主要逻辑是可手动调用、api调用、定时调用
# 调用后执行仓库下的update.sh 并使用 secrets.GT (对应值为申请的github token) 完成commit并推送

name: up
on:
  # 手动调用
  workflow_dispatch:

  # 定时调用(每天1次)
  schedule:
    - cron: '0 0 * * *'

jobs:
  up:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate 3D contribution profile
        uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GT }}
          USERNAME: ${{ github.repository_owner }}
          SETTING_JSON: ./3d-profile.json
      - run: mv ./profile-3d-contrib/* ./ && rmdir profile-3d-contrib
      - name: Run update script
        run: |
          bash update.sh
      - name: Commit & Push
        run: |
          remote_addr=`git remote get-url --push origin`
          remote_addr=`echo $remote_addr|  awk -F '://' '{print $2}'`
          remote_addr=https://${user_name}:${{ secrets.GT }}@${remote_addr}
          git status
          git diff
          git config  user.name "yaocccc"
          git config  user.email "flyforest@outlook.com"
          git remote add action ${remote_addr}
          git add --all
          git commit -m "BY:GITHUB ACTION -- $(date '+%Y/%m/%d %H:%M')"
          git push action HEAD:master --force
